---
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    expose:
      - 3000
    environment:
      DATABASE_URL: postgresql://${UMAMI_POSTGRES_USER:-umami}:${UMAMI_POSTGRES_PASSWORD:?Set this in the local secrets.env file}@db:5432/${UMAMI_POSTGRES_DB:-umami}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${UMAMI_APP_SECRET:?Set this in the local secrets.env file}
      VIRTUAL_HOST: umami.mv-angelbachtal.de
      VIRTUAL_PORT: "3000"
      LETSENCRYPT_HOST: umami.mv-angelbachtal.de
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: ${UMAMI_POSTGRES_PASSWORD:?Set this in the local secrets.env file}
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      default:
      grafana:
        aliases:
          - umami_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db:

networks:
  proxy:
    external: true
  grafana:
    external: true

